name: check-latest-migration
on:
  pull_request:

jobs: 
  check-latest-migration:
    name: Check latest migration
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v5
        with: 
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.SSM_AUTH }}

      - name: Check the latest migration version
        run: 
          ./scripts/check-latest-migration.sh
